[project]
name = "dotfiles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
]

[tool.uv.workspace]
members = [
    "train_server",
    "train_server/testing/MTAPI",
    "utils",
]
